[package]
name = "simple-pixels"
version = "0.1.0"
description = "Create a window and throw some pixels on it without accessing low-level stuff, carrying tons of dependencies or linking C libraries"
authors = ["Solar-Falcon"]
edition = "2021"
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Solar-Falcon/simple-pixels"
categories = ["rendering::engine"]

[dependencies]
fnv = "1.0"
miniquad = "0.3.12"
rgb = "0.8"